### PR TITLE
Add package-lock.json

### PR DESCRIPTION
**Pull request by berezovskyi**

### CODE REVIEW

**Comment by berezovskyi** [comment]
I think committing node_modules is an anti-pattern. Should we have a `package.json` and a `package-lock.json` instead?

**Comment by berezovskyi** [comment]
But wait, this PR did not remove the node_modules folder and I don't have the package.json file on my machine

**Comment by berezovskyi** [comment]
Do you have one?

**Comment by FabioRNT** [comment]
> Do you have one?

The package.lock file was pulled in the last pull that I've made. However, the node_modules wasn't removed yet. Should we remove it then?

**Comment by berezovskyi** [comment]
lockfile was indeed merged in. but not the package.json descriptor itself

I found this https://stackoverflow.com/questions/50038891/create-package-json-from-package-lock-json and I think it might be just what we need

**Comment by berezovskyi** [comment]
but can you add that json in  a new PR?

**Comment by FabioRNT** [comment]
> but can you add that json in a new PR?

Sure, I'll create a PR with the actual droplet configs, so you can check it

**Pull request merged**
